version: '3.8'

services:
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - db:/data/db

volumes:
  db:
